### ISSUE TITLE
Double == Double always yields false

### ISSUE THREAD

**Issue by stardisblue** [Caster/growing-glyphs#1]
Hello, after tinkering with the code:
https://github.com/Caster/growing-glyphs/blob/fc4d25133d74ebc6a2db803f0dc8ef2183fa8fb7/src/algorithm/FirstMergeRecorder.java#L381
Is never true since `Double` objects are not `==` with each-other in Java.

**Comment by Caster** [comment]
Thank you for the feedback, @stardisblue! Out of curiosity, did you encounter odd behavior, or were you looking through the code when encountering this? I think this case seldomly occurs, so it might be good to find a test case that triggers it.

As to resolving this: I believe using `Utils.Double#eq` would fix this, agreed?

**Comment by stardisblue** [comment]
It triggers during csv/glottovis.tsv using big as a strategy. I had different stats when I fixed it...

**Comment by stardisblue** [comment]
btw, i'm wondering about two things : 
1. how would you stop the clustering at a certain step (for example, i don't need to calculate until full convergence but just until 1 equals 10base units).
2. I have trouble extracting the result value of the clustering ; in accordance to step1. Since it gives me the ultimate cluster.

**Comment by Caster** [comment]
Let me answer your followup questions in #2, @stardisblue :slightly_smiling_face:
