### ISSUE TITLE
QUAD vs QUAD+

### ISSUE THREAD

**Issue by stardisblue** [Caster/growing-glyphs#3]
Hello,

While porting to Typescript there is something that I struggle to understand.

When using the QUAD strategy, ROBUST is set to true: 
https://github.com/Caster/growing-glyphs/blob/7e1e931af3f74fc1fe5caaeb0e100c4d6377578c/src/ui/CLI.java#L74-L81

When using the `plus` strategy (that I understood as QUAD+) sets ROBUST to false by default.

However, If I go a little further; during the clustering phase.
https://github.com/Caster/growing-glyphs/blob/7e1e931af3f74fc1fe5caaeb0e100c4d6377578c/src/ui/GrowingGlyphsDaemon.java#L102-L103
Meaning that if `ROBUST` is set to true it's QUAD+, and if it is false it's just QUAD ?

My intuition here is that QUAD+ is when ROBUST is set to false. Is that the case ?
Thank you :).

**Comment by Caster** [comment]
Thank you for the heads up @stardisblue, this is indeed confusing. The log message is incorrect, your intuition is right. `ROBUST` indicates that the optimization is *not* being used, so indeed QUAD+ (and QUAD+BIG) have `ROBUST` set to `false`.
